#!/bin/bash	
#PBS -N Bwa-Continue
#PBS -l nodes=1:ppn=16
#PBS -l vmem=100gb
#PBS -l walltime=24:00:00
#PBS -M ouqd@hotmail.com
#PBS -m abe
#PBS -j oe

set -x
module load samtools
module load java

ulimit -s
cd time /N/u/xw63/Carbonate/daphnia/DaphniaVariantCall
set +x

echo ===============================================================
echo 14. Make the mpileup file from the BAM file.
echo ===============================================================

set -x
	

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-001-RG_Sorted_dedup_realigned_Clipped.bam > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-001.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-002-RG_Sorted_dedup_realigned_Clipped.bam > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-002.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003-RG_Sorted_dedup_realigned_Clipped.bam > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-003.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-004-RG_Sorted_dedup_realigned_Clipped.bam > /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-004.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-005-RG_Sorted_dedup_realigned_Clipped.bam >  /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-005.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-006-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-006.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-007-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-007.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-008-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-008.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-012-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-012.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-013-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-013.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-014-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-014.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-015-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-015.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-018-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-018.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-021-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-021.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-022-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-022.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-025-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-025.mpileup &

time /N/soft/rhel6/samtools/1.3.1/bin/samtools mpileup -f PA42.4.1.fasta /N/dc2/scratch/xw63/PA2013/Bwa/PA2013-027-RG_Sorted_dedup_realigned_Clipped.bam >/N/dc2/scratch/xw63/PA2013/Bwa/PA2013-027.mpileup &


wait

set +x
echo ===============================================================
echo =============Task completed.===================
echo ===============================================================
	

