#!/bin/bash 
#PBS -N mapgd-parallel-proview
#PBS -k o
#PBS -l nodes=1:ppn=16,walltime=12:00:00
#PBS -l vmem=100gb
#PBS -M ouqd@hotmail.com
#PBS -m abe
#PBS -j oe

# Updated on 05/28/2018

set +x 
module rm gcc
module load gcc
module load gsl  

module load samtools
set -x
cd /N/dc2/scratch/xw63/PA2013/Bwa
set +x
echo ===============================================================
echo 0. Make a header file
echo ===============================================================
time samtools view -H PA2013-001-RG_Sorted_dedup_realigned_Clipped.bam > /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header
echo ===============================================================
echo 1. Make a pro file of nucleotide-read quartets -counts of A, C, G, and T, from each of the mpileup files of the clones.
echo ===============================================================
set -x
date
			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-002.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-002.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-003.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-003.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-004.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-004.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-005.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-005.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-006.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-006.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-007.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-007.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-008.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-008.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-012.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-012.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-013.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-013.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-014.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-014.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-015.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-015.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-018.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-018.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-021.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-021.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-022.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-022.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-025.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-025.proview &

			
time /N/dc2/projects/daphpops/Software/MAPGD-0.4.26/bin/mapgd proview -i PA2013-027.mpileup -H /N/dc2/scratch/xw63/PA2013/Bwa/PA42.header > PA2013-027.proview &

wait

date

echo ===============================================================
echo =============Task completed.===================
echo ===============================================================
